#######################################################################################
# Training
#######################################################################################
batch_size: 16
val_batch_size: 16
num_epochs: 5
description: Forecast_2D
multiprocessing: false
device: cuda:0
seed: 0
wandb_mode: online
pretrained_path: '/pscratch/sd/r/rgeorge/checkpoint1/MAE_Aug_fno_64_mask0.5_aug0.5_971140.pth'
freeze: false
normalize: false
verbose: false
add_vars: false 

#######################################################################################
# Model
#######################################################################################
encoder: FNO2D
pad: False
pos_mode: none
temporal_patch_size: 4
masking_ratio: 0.9
scheduler: onecycle
min_lr: 0.0001
max_lr: 0.001
beta1: 0.9
beta2: 0.98
pct_start: 0.2
div_factor: 10
final_div_factor: 1000
dropout: 0.0
emb_dropout: 0.0
embedding_dim: 32 # this is channels
embedding_dim_time: 64 # double of last
n_modes: [8, 32, 32]
in_dim: 1
out_dim: 128
n_layers: 1
encoder_width: 128
decoder_modes: [8, 32, 32]
decoder_width: 128
decoder_layers: 1

#######################################################################################
# Data
#######################################################################################
pde: heat_adv_burgers
pde_dim: 2
n_vars: 5
norm_vars: false
num_samples: 10
train_path: /pscratch/sd/r/rgeorge/hong/2D/train/HeaAdvBurgers_3072.h5
valid_path: /pscratch/sd/r/rgeorge/hong/2D/valid/HeaAdvBurgers_768.h5
norm_stat_path: checkpoints/stats/Stats_HeatAdvBurgers_2D_train.pkl
base_resolution: [100, 64, 64]
t_range: [0, 2]
x_range: [-1, 1]
load_all: true
time_window: 16
augmentation_ratio: 0.0
max_shift: 0.5
max_velocity: 0.5
max_scale: 0.5
max_nodal_shift: 0.25
encoder_embedding_dim: 0
embedding_mode: none
sizes: []

#######################################################################################
# Timestepper
#######################################################################################
model: FNO2D
fno_modes: 12
fno_width: 48
fno_num_layers: 4
unet_hidden_channels: 16
timestep_lr: 0.0008
timestep_lr_min: 0.0001
unrolling: 1
nr_gt_steps: 2
horizon: 96


