#######################################################################################
# Training
#######################################################################################
batch_size: 24
val_batch_size: 24
num_epochs: 10
n_inner: 1
description: SR_2D
multiprocessing: false
device: cuda:0
seed: 0
wandb_mode: online
pretrained_path: '/pscratch/sd/r/rgeorge/checkpoint1/MAE_Aug_fno_64_mask0.5_aug0.5_971140.pth' #'/pscratch/sd/r/rgeorge/checkpoint1/MAE_Aug_VIT3D_64_mask0.9_aug0.5_971413.pth' 
freeze: false
normalize: false
verbose: false
add_vars: false 

#######################################################################################
# Model
#######################################################################################
encoder: FNO2D
pad: False
pos_mode: none
encoder_pool: cls
encoder_dim: 256
encoder_mlp_dim: 512
encoder_heads: 32
encoder_dim_head: 32
encoder_depth: 8
encoder_temporal_depth: 4
decoder_dim: 32
decoder_depth: 4
decoder_heads: 16
decoder_dim_head: 16
image_size: [64, 64]
patch_size: [4, 4]
temporal_patch_size: 4
masking_ratio: 0.9
scheduler: onecycle
min_lr: 0.0001
max_lr: 0.001
beta1: 0.9
beta2: 0.98
pct_start: 0.2
div_factor: 10
final_div_factor: 1000
dropout: 0.0
emb_dropout: 0.0
embedding_dim: 32
n_modes: [8, 32, 32]
in_dim: 1
out_dim: 128
n_layers: 1
encoder_width: 128
decoder_modes: [8, 32, 32]
decoder_width: 128
decoder_layers: 1

#######################################################################################
# Data
#######################################################################################
pde: heat_adv_burgers
pde_dim: 2
n_vars: 5
norm_vars: false
num_samples: 1024
train_path: /pscratch/sd/r/rgeorge/hong/2D/train/HeaAdvBurgers_3072.h5
valid_path: /pscratch/sd/r/rgeorge/hong/2D/valid/HeaAdvBurgers_768.h5
norm_stat_path: checkpoints/stats/Stats_HeatAdvBurgers_2D_train.pkl
base_resolution: [100, 32, 32]
t_range: [0, 2]
x_range: [-1, 1]
load_all: true
time_window: 16
augmentation_ratio: 0.0
max_shift: 0.5
max_velocity: 0.5
max_scale: 0.5
max_nodal_shift: 0.25
encoder_embedding_dim: 0
embedding_mode: none
size_low: 32
scale_factor: 2 


#######################################################################################
# Timestepper
#######################################################################################
operator: FNO2D
fno_modes: 12
fno_width: 48
fno_num_layers: 4
unet_hidden_channels: 16
timestep_lr: 0.0008
timestep_lr_min: 0.0001
unrolling: 1
nr_gt_steps: 2
horizon: 96

network: Resnet2D
resnet_features: 32
resnet_embedd: 64 #this is for the numb of channels in embedd * time = embedd for fourier
resnet_blocks: 4