#######################################################################################
# Training
#######################################################################################
batch_size: 64
val_batch_size: 64
num_epochs: 1
description: MAE_Aug
multiprocessing: false
device: cuda:0
seed: 0
wandb_mode: online
n_inner: 5
pretrained_path: none
freeze: false
normalize: false

#######################################################################################
# Model
#######################################################################################
encoder: FNO2D
pad: False
pos_mode: none
temporal_patch_size: 4
masking_ratio: 0.5
scheduler: onecycle
min_lr: 0.0001
max_lr: 0.001
beta1: 0.9
beta2: 0.98
pct_start: 0.2
div_factor: 10
final_div_factor: 1000
dropout: 0.0
emb_dropout: 0.0
n_modes: [8, 32, 32]
in_dim: 1
out_dim: 128
n_layers: 1
encoder_width: 128
decoder_modes: [8, 32, 32]
decoder_width: 128
decoder_layers: 1

#######################################################################################
# Data
#######################################################################################
pde: heat_adv_burgers
pde_dim: 2
norm_vars: false
num_samples: 10
pretrain_path: /pscratch/sd/r/rgeorge/hong/2D/pretrain/HeaAdvBurgers_12288.h5
train_path: /pscratch/sd/r/rgeorge/hong/2D/train/HeaAdvBurgers_3072.h5
valid_path: /pscratch/sd/r/rgeorge/hong/2D/valid/HeaAdvBurgers_768.h5
norm_stat_path: checkpoints/stats/Stats_HeatAdvBurgers_2D_Pretrain.pkl
base_resolution: [100, 64, 64]
t_range: [0, 2]
x_range: [-1, 1]
load_all: false
time_window: 16
augmentation_ratio: 0.5
max_shift: 0.5
max_velocity: 0.5
max_scale: 0.5
max_nodal_shift: 0.25
horizon: 96
encoder_embedding_dim: 0
embedding_mode: none
sizes: []
#sizes: [[64, 64], [64, 60], [64, 56], [64, 52], [60, 64], [60, 60], [60, 56], [60, 52], [56, 64], [56, 60], [56, 56], [56, 52], [52, 64], [52, 60], [52, 56], [52, 52]]


