#######################################################################################
# Training
#######################################################################################
batch_size: 64
val_batch_size: 64
num_epochs: 20
description: MAE_Aug
multiprocessing: false
device: cuda:1
seed: 0
wandb_mode: online
n_inner: 5
pretrained_path: none
freeze: false
normalize: false

#######################################################################################
# Model
#######################################################################################
encoder: VIT3D
pad: False
pos_mode: interpolate
encoder_pool: cls
encoder_dim: 256
encoder_mlp_dim: 512
encoder_heads: 32
encoder_dim_head: 32
encoder_depth: 8
encoder_temporal_depth: 4
decoder_dim: 32
decoder_depth: 4
decoder_heads: 16
decoder_dim_head: 16
image_size: [64, 64]
patch_size: [4, 4]
temporal_patch_size: 4
masking_ratio: 0.9
scheduler: onecycle
min_lr: 0.0001
max_lr: 0.001
beta1: 0.9
beta2: 0.98
pct_start: 0.2
div_factor: 10
final_div_factor: 1000
dropout: 0.0
emb_dropout: 0.0

#######################################################################################
# Data
#######################################################################################
pde: heat_adv_burgers
pde_dim: 2
norm_vars: false
num_samples: 12288
pretrain_path: YOUR_PATH_TO_PRETRAIN_DATA
train_path: YOUR_PATH_TO_TRAINING_DATA
valid_path: YOUR_PATH_TO_VALID_DATA
norm_stat_path: checkpoints/stats/Stats_HeatAdvBurgers_2D_Pretrain.pkl
base_resolution: [100, 64, 64]
t_range: [0, 2]
x_range: [-1, 1]
load_all: false
time_window: 16
augmentation_ratio: 0.5
max_shift: 0.5
max_velocity: 0.5
max_scale: 0.5
max_nodal_shift: 0.25
horizon: 96
encoder_embedding_dim: 256
embedding_mode: spatial
#sizes: []
sizes: [[64, 64], [60, 60], [56, 56], [52, 52], [48, 48]]


